manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: garrettfaucher
      url-base: https://github.com/garrettfaucher
    - name: urob
      url-base: https://github.com/urob
    - name: kotkota
      url-base: https://github.com/kotkota
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    # - name: zmk-dongle-display-091-oled
    #   remote: garrettfaucher
    #   revision: main
    - name: zmk-driver-pmw3360
      remote: garrettfaucher
      revision: invert-x-y
    - name: zmk-leader-key
      remote: urob
      revision: v0.3
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.3
    - name: zmk-auto-layer
      remote: urob
      revision: v0.3
    - name: zmk-dongle-display-view
      remote: kotkota
      revision: main
  self:
    path: config
